language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
  - webdriver-manager update --standalone
  - npm install -g grunt-cli
  - rm -rf node_modules
  - npm cache clean
install: npm install
services:
  - mongodb
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
