language: node_js
compiler:
  - gcc
node_js:
  - "0.11"
  - "0.10"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - webdriver-manager update --standalone
  - node node_modules/protractor/bin/webdriver-manager update --standalone
  - npm install -g grunt-cli
install: npm rebuild
services:
  - mongodb
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
