language: node_js
env:
  SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true
compiler:
  - gcc
node_js:
  - "0.11"
  - "0.10"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo apt-get update;
  - sudo apt-get install gcc-4.8 g++-4.8;
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20;
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20;
  - g++ --version;
  - sudo apt-get update -qq;
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - webdriver-manager update --standalone
  - npm install -g grunt-cli
  - npm install node-sass-middleware
install: npm rebuild
services:
  - mongodb
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
