language: node_js
compiler:
  - gcc
node_js:
  - "5.1.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g grunt-cli
cache:
  directories:
  - node_modules
services:
  - mongodb
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
notifications:
  email: false
