language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
  - npm cache clean
  - npm install -g grunt-cli
  - npm install karma-phantomjs-launcher
  - npm install mongodb
  - npm install bson
services:
  - mongodb
