language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - webdriver-manager update --standalone
  - npm install -g grunt-cli
  - npm install node-sass-middleware
install: npm rebuild
services:
  - mongodb
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
