web:
  build: .
  ports:
    - "3000:3000"
  links:
    - "mongo:mongo"
    - "seleniumhub:hub"
  volumes:
    - public:/usr/src/app/public
    - server:/usr/src/app/server
    - views:/usr/src/app/views
    - test:/usr/src/app/test
    - package.json:/usr/src/app/package.json
    - config.js:/usr/src/app/config.js
    - Gruntfile.js:/usr/src/app/Gruntfile.js
mongo:
  image: mongo
  environment:
    - AUTH=no
seleniumhub:
  image: selenium/hub
seleniumnode1:
  image: selenium/node-chrome
  links:
    - "seleniumhub:hub"
    - "web:web"
  volumes:
    - screenshots:/tmp/screenshots

#seleniumhub:
#  image: benschw/selenium-hub
#seleniumnode1:
#  image: benschw/selenium-node-firefox
#  links:
#    - "seleniumhub:hub"
#seleniumnode2:
#  image: benschw/selenium-node-firefox
#  links:
#    - "seleniumhub:hub"
#seleniumnode3:
#  image: benschw/selenium-node-firefox
#  links:
#    - "seleniumhub:hub"