web:
  hostname: web
  build: .
  ports:
    - "3000:3000"
  links:
    - "mongo:mongo"
    - "seleniumhub:hub"
    - "statsd:statsd"
  volumes:
    - ./public:/usr/src/app/public
    - ./server:/usr/src/app/server
    - ./views:/usr/src/app/views
    - ./test:/usr/src/app/test
    - ./package.json:/usr/src/app/package.json
    - ./config.js:/usr/src/app/config.js
    - ./Gruntfile.js:/usr/src/app/Gruntfile.js
    - ./karma.conf.js:/usr/src/app/karma.conf.js
    - ./test-output:/usr/src/app/test-output
mongo:
  image: mongo
  environment:
    - AUTH=no
  volumes:
    - ./data/db:/data/db
statsd:
  image: hopsoft/graphite-statsd
  ports:
    - "3002:80"
    - "2003:2003"
    - "8125:8125/udp"
grafana:
  image: grafana/grafana
  links:
    - statsd
  ports:
    - "3001:3000"
seleniumhub:
  image: selenium/hub
chromenode:
  image: selenium/node-chrome
  volumes:
    - /dev/shm:/dev/shm
  links:
    - "seleniumhub:hub"
    - "web:web"
